<?php

use Illuminate\Database\Seeder;

class NeighborhoodTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('neighborhoods')->insert([
			['name' => 'Allegheny Center', 'slug' => 'allegheny-center'],
			['name' => 'Allegheny West', 'slug' => 'allegheny-west'],
			['name' => 'Allentown', 'slug' => 'allentown'],
			['name' => 'Arlington', 'slug' => 'arlington'],
			['name' => 'Arlington Heights', 'slug' => 'arlington-heights'],
			['name' => 'Banksville', 'slug' => 'banksville'],
			['name' => 'Bedford Dwellings', 'slug' => 'bedford-dwellings'],
			['name' => 'Beechview', 'slug' => 'beechview'],
			['name' => 'Beltzhoover', 'slug' => 'beltzhoover'],
			['name' => 'Bloomfield', 'slug' => 'bloomfield'],
			['name' => 'Bluff', 'slug' => 'bluff'],
			['name' => 'Bon Air', 'slug' => 'bon-air'],
			['name' => 'Brighton Heights', 'slug' => 'brighton-heights'],
			['name' => 'Brookline', 'slug' => 'brookline'],
			['name' => 'California-Kirkbride', 'slug' => 'california-kirkbride'],
			['name' => 'Carrick', 'slug' => 'carrick'],
			['name' => 'Central Business District', 'slug' => 'central-business-district'],
			['name' => 'Cultural District', 'slug' => 'cultural-district'],
			['name' => 'Central Lawrenceville', 'slug' => 'central-lawrenceville'],
			['name' => 'Central Northside', 'slug' => 'central-northside'],
			['name' => 'Mexican War Streets', 'slug' => 'mexican-war-streets'],
			['name' => 'Central Oakland', 'slug' => 'central-oakland'],
			['name' => 'Chartiers', 'slug' => 'chartiers'],
			['name' => 'Chateau', 'slug' => 'chateau'],
			['name' => 'Crafton Heights', 'slug' => 'crafton-heights'],
			['name' => 'Crawford-Roberts', 'slug' => 'crawford-roberts'],
			['name' => 'Duquesne Heights', 'slug' => 'duquesne-heights'],
			['name' => 'East Allegheny', 'slug' => 'east-allegheny'],
			['name' => 'East Carnegie', 'slug' => 'east-carnegie'],
			['name' => 'East Hills', 'slug' => 'east-hills'],
			['name' => 'East Liberty', 'slug' => 'east-liberty'],
			['name' => 'Elliott', 'slug' => 'elliott'],
			['name' => 'Esplen', 'slug' => 'esplen'],
			['name' => 'Fairywood', 'slug' => 'fairywood'],
			['name' => 'Fineview', 'slug' => 'fineview'],
			['name' => 'Friendship', 'slug' => 'friendship'],
			['name' => 'Garfield', 'slug' => 'garfield'],
			['name' => 'Glen Hazel', 'slug' => 'glen-hazel'],
			['name' => 'Greenfield', 'slug' => 'greenfield'],
			['name' => 'Four Mile Run', 'slug' => 'four-mile-run'],
			['name' => 'Hays', 'slug' => 'hays'],
			['name' => 'Hazelwood', 'slug' => 'hazelwood'],
			['name' => 'Highland Park', 'slug' => 'highland-park'],
			['name' => 'Homewood North', 'slug' => 'homewood-north'],
			['name' => 'Homewood South', 'slug' => 'homewood-south'],
			['name' => 'Homewood West', 'slug' => 'homewood-west'],
			['name' => 'Knoxville', 'slug' => 'knoxville'],
			['name' => 'Larimer', 'slug' => 'larimer'],
			['name' => 'Lincoln–Lemington–Belmar', 'slug' => 'lincoln–lemington–belmar'],
			['name' => 'Lincoln Place', 'slug' => 'lincoln-place'],
			['name' => 'Lower Lawrenceville', 'slug' => 'lower-lawrenceville'],
			['name' => 'Manchester', 'slug' => 'manchester'],
			['name' => 'Marshall-Shadeland', 'slug' => 'marshall-shadeland'],
			['name' => 'Middle Hill', 'slug' => 'middle-hill'],
			['name' => 'Morningside', 'slug' => 'morningside'],
			['name' => 'Mount Oliver', 'slug' => 'mount-oliver'],
			['name' => 'Mount Washington', 'slug' => 'mount-washington'],
			['name' => 'Chatham Village', 'slug' => 'chatham-village'],
			['name' => 'New Homestead', 'slug' => 'new-homestead'],
			['name' => 'North Oakland', 'slug' => 'north-oakland'],
			['name' => 'North Point Breeze', 'slug' => 'north-point-breeze'],
			['name' => 'North Shore', 'slug' => 'north-shore'],
			['name' => 'Northview Heights', 'slug' => 'northview-heights'],
			['name' => 'Oakwood', 'slug' => 'oakwood'],
			['name' => 'Overbrook', 'slug' => 'overbrook'],
			['name' => 'Perry North', 'slug' => 'perry-north'],
			['name' => 'Perry South', 'slug' => 'perry-south'],
			['name' => 'Point Breeze', 'slug' => 'point-breeze'],
			['name' => 'Polish Hill', 'slug' => 'polish-hill'],
			['name' => 'Regent Square', 'slug' => 'regent-square'],
			['name' => 'Ridgemont', 'slug' => 'ridgemont'],
			['name' => 'Saint Clair', 'slug' => 'saint-clair'],
			['name' => 'Shadyside', 'slug' => 'shadyside'],
			['name' => 'Sheraden', 'slug' => 'sheraden'],
			['name' => 'South Oakland', 'slug' => 'south-oakland'],
			['name' => 'Panther Hollow', 'slug' => 'panther-hollow'],
			['name' => 'Southshore', 'slug' => 'southshore'],
			['name' => 'South Side Flats', 'slug' => 'south-side-flats'],
			['name' => 'South Side Slopes', 'slug' => 'south-side-slopes'],
			['name' => 'Spring Garden', 'slug' => 'spring-garden'],
			['name' => 'Spring Hill–City View', 'slug' => 'spring-hill–city-view'],
			['name' => 'Squirrel Hill North', 'slug' => 'squirrel-hill-north'],
			['name' => 'Squirrel Hill South', 'slug' => 'squirrel-hill-south'],
			['name' => 'Summerset at Frick Park', 'slug' => 'summerset-at-frick-park'],
			['name' => 'Stanton Heights', 'slug' => 'stanton-heights'],
			['name' => 'Strip District', 'slug' => 'strip-district'],
			['name' => 'Summer Hill', 'slug' => 'summer-hill'],
			['name' => 'Swisshelm Park', 'slug' => 'swisshelm-park'],
			['name' => 'Terrace Village', 'slug' => 'terrace-village'],
			['name' => 'Troy Hill', 'slug' => 'troy-hill'],
			['name' => 'Washington\'s Landing', 'slug' => 'washington-landing'],
			['name' => 'Upper Hill', 'slug' => 'upper-hill'],
			['name' => 'Upper Lawrenceville', 'slug' => 'upper-lawrenceville'],
			['name' => 'West End', 'slug' => 'west-end'],
			['name' => 'West Oakland', 'slug' => 'west-oakland'],
			['name' => 'Westwood', 'slug' => 'westwood'],
			['name' => 'Windgap', 'slug' => 'windgap'],
        ]);
    }
}
